# Generated by Django 6.0.5 on 2026-08-12 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, default='', help_text='Telegram Bot Token from @BotFather', max_length=255)),
                ('bot_username', models.CharField(blank=True, default='', help_text='Telegram Bot Username (e.g. DeployOpsBot)', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('cpu_threshold', models.FloatField(default=80.0, help_text='CPU percentage overload threshold')),
                ('ram_threshold', models.FloatField(default=85.0, help_text='RAM percentage overload threshold')),
                ('disk_threshold', models.FloatField(default=90.0, help_text='Disk percentage overload threshold')),
                ('notify_server_overload', models.BooleanField(default=True)),
                ('notify_github_push', models.BooleanField(default=True)),
                ('last_update_id', models.BigIntegerField(default=0, help_text='Offset for getUpdates polling')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('telegram_username', models.CharField(blank=True, default='', max_length=150)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('verification_token', models.CharField(db_index=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_subscribers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, default='', max_length=100)),
                ('notification_type', models.CharField(choices=[('SERVER_OVERLOAD', 'Server Overload Alert'), ('GITHUB_PUSH', 'GitHub Push Notification'), ('TEST', 'Test Notification'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(default='SENT', max_length=50)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='telegram_monitoring.telegramsubscriber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
