# Generated by Django 6.0.5 on 2026-08-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramconfig',
            name='notify_database_backup',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='telegramnotificationlog',
            name='notification_type',
            field=models.CharField(choices=[('SERVER_OVERLOAD', 'Server Overload Alert'), ('GITHUB_PUSH', 'GitHub Push Notification'), ('DATABASE_BACKUP', 'Database Backup Notification'), ('TEST', 'Test Notification'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=50),
        ),
    ]
