# Generated by Django 6.0.5 on 2026-08-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_monitoring', '0002_telegramconfig_notify_database_backup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramconfig',
            name='daily_report_enabled',
            field=models.BooleanField(default=True, help_text='Send daily service health report to Telegram'),
        ),
        migrations.AddField(
            model_name='telegramconfig',
            name='daily_report_time',
            field=models.CharField(default='21:00', help_text='Time to send daily report in HH:MM format (24hr, e.g. 21:00 for 9:00 PM)', max_length=10),
        ),
        migrations.AddField(
            model_name='telegramconfig',
            name='last_daily_report_sent',
            field=models.DateField(blank=True, help_text='Date when daily report was last sent', null=True),
        ),
        migrations.AlterField(
            model_name='telegramnotificationlog',
            name='notification_type',
            field=models.CharField(choices=[('SERVER_OVERLOAD', 'Server Overload Alert'), ('GITHUB_PUSH', 'GitHub Push Notification'), ('DATABASE_BACKUP', 'Database Backup Notification'), ('DAILY_REPORT', 'Daily Service Health Report'), ('TEST', 'Test Notification'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=50),
        ),
    ]
