# Generated by Django 6.0.7 on 2026-08-01 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server_monitoring', '0002_metricreading_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('django', 'Django'), ('gunicorn', 'Gunicorn'), ('nginx', 'Nginx'), ('celery', 'Celery'), ('system', 'System')], max_length=50)),
                ('level', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('DEBUG', 'DEBUG')], default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='server_monitoring.server')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['server', 'log_type', 'level', 'timestamp'], name='log_monitor_server__764703_idx')],
            },
        ),
    ]
