# Generated by Django 6.0.5 on 2026-08-06 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=50.0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('email_alert', models.EmailField(blank=True, max_length=254, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='aws_monitoring.awsaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
