# Generated by Django 6.0.7 on 2026-08-01 14:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('public_ip', models.CharField(blank=True, max_length=50)),
                ('private_ip', models.CharField(blank=True, max_length=50)),
                ('environment', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cpu_model', models.CharField(blank=True, max_length=255)),
                ('total_ram', models.BigIntegerField(default=0)),
                ('total_disk', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cpu', models.FloatField()),
                ('ram', models.FloatField()),
                ('disk', models.FloatField()),
                ('uptime', models.FloatField()),
                ('disk_free', models.BigIntegerField(default=0)),
                ('disk_used', models.BigIntegerField(default=0)),
                ('swap_percent', models.FloatField(default=0.0)),
                ('network_upload', models.BigIntegerField(default=0)),
                ('network_download', models.BigIntegerField(default=0)),
                ('load_average_1m', models.FloatField(default=0.0)),
                ('load_average_5m', models.FloatField(default=0.0)),
                ('load_average_15m', models.FloatField(default=0.0)),
                ('process_count', models.IntegerField(default=0)),
                ('top_processes', models.JSONField(blank=True, default=list)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='server_monitoring.server')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['server', 'timestamp'], name='server_moni_server__f869cb_idx')],
            },
        ),
    ]
