# Generated by Django 6.0.7 on 2026-08-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricreading',
            name='services',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
