# Generated by Django 6.0.7 on 2026-08-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project Display Name', max_length=255)),
                ('github_owner', models.CharField(help_text='GitHub Account or Organization Name (e.g. Shailesh-2128)', max_length=255)),
                ('github_repo', models.CharField(help_text='Repository Name (e.g. king_wins_backend)', max_length=255)),
                ('github_token', models.TextField(blank=True, default='', help_text='Encrypted GitHub Personal Access Token')),
                ('default_branch', models.CharField(default='main', help_text='Default Branch (e.g. main, master)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('github_owner', 'github_repo')},
            },
        ),
    ]
