# Generated by Django 6.0.7 on 2026-08-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
