# Generated by Django 6.0.5 on 2026-08-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('servers', 'Server Monitoring'), ('websites', 'Website Monitoring'), ('databases', 'Database Monitoring'), ('github', 'GitHub Monitoring'), ('aws', 'AWS Cloud Monitoring'), ('aws_costing', 'AWS Costing'), ('telegram', 'Telegram Notifications'), ('iam', 'User & IAM Management')], default='iam', max_length=50),
        ),
    ]
