# Generated by Django 6.0.7 on 2026-08-01 14:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('expected_status', models.IntegerField(default=200)),
                ('check_interval', models.IntegerField(default=60)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('ssl_expiry', models.DateField(blank=True, null=True)),
                ('ssl_valid', models.BooleanField(default=True)),
                ('redirected', models.BooleanField(default=False)),
                ('redirect_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='website_monitoring.website')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['website', 'checked_at'], name='website_mon_website_25152c_idx')],
            },
        ),
    ]
