# Generated by Django 6.0.7 on 2026-08-01 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('db_type', models.CharField(choices=[('Supabase', 'Supabase'), ('Neon', 'Neon'), ('Local PostgreSQL', 'Local PostgreSQL'), ('AWS RDS PostgreSQL', 'AWS RDS PostgreSQL'), ('MySQL', 'MySQL'), ('MongoDB', 'MongoDB')], max_length=50)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('database_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_uri', models.TextField(blank=True, null=True)),
                ('check_interval', models.IntegerField(default=60)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('database_size', models.BigIntegerField(blank=True, null=True)),
                ('active_connections', models.IntegerField(blank=True, null=True)),
                ('long_running_queries', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='database_monitoring.database')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['database', 'checked_at'], name='database_mo_databas_5efb45_idx')],
            },
        ),
    ]
