# Generated by Django 6.0.5 on 2026-08-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='api_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='project_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
